name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Install native dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libavcodec-dev \
          libavutil-dev \
          libsdl2-dev \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxinerama-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libxxf86vm-dev \
          libasound2-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
